---@meta nitr
-- GENERATED by `nitr` from nitr-api.toml — do not edit by hand.
-- Editor completion for the whole `nitr.*` surface: keep this file
-- next to your scripts (the Lua Language Server picks it up).

---@class nitr
nitr = {}

---The incoming request, passed to every handler and middleware.
---@class nitr.Request
---@field method string Request method, uppercase (`"GET"`).
---@field path string URI path (`"/users/42"`).
---@field params table<string, string> Path parameters captured by the router (`:id` → `params.id`).
---@field query table<string, string> Parsed query string; repeated keys keep the last value.
---@field headers table<string, string> Request headers, lowercase names.
---@field id string The request id (UUIDv7, echoed as `X-Request-ID`).
---@field remote_addr string Peer address (`"ip:port"`).
---@field uri table URI components: `scheme`, `host`, `port`, `path`, `authority`, `query`.
---@field cookies nitr.RequestCookies Parsed request cookies.
local Request = {}

---Reads and decodes the body as JSON. Errors on an empty or invalid body.
---@return table
function Request:json() end

---Reads the whole body as a string.
---@return string
function Request:text() end

---Reads an `application/x-www-form-urlencoded` body as a table. The parse is cached, so middleware and handler can both call it.
---@return table<string, string>
function Request:form() end

---Invokes `fn(part)` once per part of a `multipart/form-data` body, in arrival order; returns the part count. (Needs the `multipart` Cargo feature.)
---@param fn fun(part: nitr.Part)
---@return integer _ Number of parts seen.
function Request:multipart(fn) end

---Streams the body: the next chunk as it arrives, or at least `n` bytes. `nil` marks the end.
---@param n? integer Minimum bytes to gather.
---@return string|nil
function Request:read(n) end

---The best match among the given media types for the `Accept` header, or nil.
---@param ... string Offered media types.
---@return string|nil
function Request:accepts(...) end

---Whether the client's cached copy is current, per `If-None-Match`/`If-Modified-Since`.
---@param etag? string Entity tag of the current representation.
---@param last_modified? integer Unix seconds of the last change.
---@return boolean
function Request:fresh(etag, last_modified) end

---Cookies from the `Cookie` header: index by name (`req.cookies.session`).
---@class nitr.RequestCookies
local RequestCookies = {}

---The verified value of a signed cookie, or nil when missing or tampered.
---@param name string
---@param secret string
---@return string|nil
function RequestCookies:verify(name, secret) end

---A response: `{ status, headers, body }` plus a cookie builder. Helpers build these; handlers may also build them by hand.
---@class nitr.Response
---@field status integer HTTP status code.
---@field headers table<string, string> Response headers.
---@field body string|fun(...)|nil Body string, or a streaming body function.
---@field cookies nitr.ResponseCookies Set-Cookie builder (attached by the helpers).
local Response = {}

---Builder for `Set-Cookie` headers on a response.
---@class nitr.ResponseCookies
local ResponseCookies = {}

---Adds a cookie. Options: `http_only`, `secure`, `path`, `domain`, `max_age` (seconds), `same_site` ("Strict"/"Lax"/"None").
---@param name string
---@param value string
---@param opts? table
function ResponseCookies:set(name, value, opts) end

---Adds an HMAC-signed cookie, verifiable later with `req.cookies:verify`.
---@param name string
---@param value string
---@param secret string
---@param opts? table
function ResponseCookies:set_signed(name, value, secret, opts) end

---The application: routes, middleware, error handling, static mounts. Return it from the handler script.
---@class nitr.App
local App = {}

---Registers a GET route: `middleware..., handler` plus an optional trailing `{ on_error = fn }`. Paths take `:name` parameters and a trailing `*` catch-all.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:get(path, ...) end

---Registers a POST route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:post(path, ...) end

---Registers a PUT route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:put(path, ...) end

---Registers a DELETE route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:delete(path, ...) end

---Registers a PATCH route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:patch(path, ...) end

---Registers a HEAD route (see `get`). Without one, HEAD reuses the GET route with the body stripped.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:head(path, ...) end

---Registers an OPTIONS route (see `get`). Without one, OPTIONS answers 204 with `Allow`.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:options(path, ...) end

---Adds app-wide middleware: a factory `fn(next) -> fn(req)`. Must be called before any route.
---@param mw fun(next: fun): fun(req: nitr.Request): any
function App:use(mw) end

---Sets the app-wide error handler: `fn(err, req)` where `err` is the structured error (`kind`, `message`, `source`, `line`, `traceback`, ...).
---@param handler fun(err: table, req: nitr.Request): nitr.Response|table
function App:on_error(handler) end

---Mounts a static directory, served in Rust. Options: `{ spa = boolean, cache_control = string }`.
---@param mount string
---@param dir string
---@param opts? table
function App:static(mount, dir, opts) end

---One part of a multipart upload, delivered to the `req:multipart` callback.
---@class nitr.Part
---@field name string|nil Form field name.
---@field filename string|nil Client-supplied file name.
---@field content_type string|nil Part content type.
local Part = {}

---Reads a non-file field as a string (bounded by `[limits] max_field_bytes`).
---@return string
function Part:text() end

---Streams a file part to `path` without entering the Lua heap; returns the bytes written.
---@param path string
---@return integer
function Part:save(path) end

---Drains and drops the part.
function Part:discard() end

---An unsent outbound request from `nitr.fetch`; send it, or hand it to `nitr.await_all`.
---@class nitr.FetchHandle
local FetchHandle = {}

---Performs the request.
---@return nitr.FetchResponse
function FetchHandle:send() end

---An outbound response.
---@class nitr.FetchResponse
---@field status integer HTTP status code.
---@field headers table<string, string> Response headers.
---@field url string Final URL after redirects.
local FetchResponse = {}

---The body as a string (bounded by `[fetch] max_response_bytes`).
---@return string
function FetchResponse:text() end

---The body decoded as JSON.
---@return table
function FetchResponse:json() end

---Streams the body chunk by chunk; `nil` at the end.
---@return string|nil
function FetchResponse:read() end

---A compiled validation schema from `nitr.validate.schema`.
---@class nitr.Schema
local Schema = {}

---Validates a value. Returns the data (declared fields only) or nil plus `{ message, fields }` mapping each failing path to its message.
---@param value any
---@return table|nil _ Validated data.
---@return table|nil _ The error, when validation failed.
function Schema:check(value) end

---A stateless signed-cookie session from `nitr.session`. Assign fields directly (`session.user_id = 42`).
---@class nitr.Session
local Session = {}

---Serializes the session into a signed cookie on the response. An empty session deletes the cookie.
---@param resp nitr.Response|table
function Session:save(resp) end

---Removes every field; `save` then writes the deletion cookie.
function Session:clear() end

---A database transaction handle inside `nitr.db:transaction`; same query API as `nitr.db`, plus nesting via savepoints.
---@class nitr.Tx
local Tx = {}

---As a function: a JSON response (`nitr.json({ ok = true })`). Also the codec: `nitr.json:encode(v)` / `nitr.json:decode(s)`. (std feature: `json`)
---@class nitr.json
---@overload fun(value: any, status: integer?): nitr.Response
nitr.json = {}

---Encodes a value as JSON.
---@param value any
---@return string
function nitr.json:encode(value) end

---Decodes JSON; errors on invalid input.
---@param s string
---@return any
function nitr.json:decode(s) end

---A `text/plain` response. (std feature: `http`)
---@param body string
---@param status? integer
---@return nitr.Response
function nitr.text(body, status) end

---A `text/html` response. (std feature: `http`)
---@param body string
---@param status? integer
---@return nitr.Response
function nitr.html(body, status) end

---A redirect (default 302). (std feature: `http`)
---@param location string
---@param status? integer
---@return nitr.Response
function nitr.redirect(location, status) end

---An empty response with the given status. (std feature: `http`)
---@param code integer
---@return nitr.Response
function nitr.status(code) end

---Picks the offer whose media type best matches the `Accept` header; function values are called with the request. No match answers 406. (std feature: `http`)
---@param req nitr.Request
---@param offers table<string, any>
---@return any
function nitr.negotiate(req, offers) end

---A Server-Sent Events stream: `fn(send)` calls `send(event, data)`; table data is JSON-encoded. (std feature: `http`)
---@param fn fun(send: fun(event: string, data: any))
---@return nitr.Response
function nitr.sse(fn) end

---An error response: string body as text, table body as JSON. (std feature: `http`)
---@param code integer
---@param body string|table|nil
---@return nitr.Response
function nitr.error(code, body) end

---A well-formed entity tag for whatever identifies the resource (a row version, an updated_at), to pair with `req:fresh`. (std feature: `http`)
---@param value any
---@param weak? boolean
---@return string
function nitr.etag(value, weak) end

---As a function: the CSRF middleware factory for `app:use` (signed double-submit cookie; unsafe methods must echo the token in `X-CSRF-Token` or a `_csrf` field). Options: `secret` (required), `cookie` (the cookie NAME, default `_csrf`), `header`, `field`, and `cookie_opts` (the cookie ATTRIBUTES, which extend the HttpOnly/SameSite=Lax defaults rather than replacing them; `http_only` cannot be un-set). Note `nitr.session` spells its attribute table `cookie` — here that key is the name. (std feature: `http`)
---@class nitr.csrf
---@overload fun(opts: table): fun
nitr.csrf = {}

---The request's token, for a form or meta tag. Requires the middleware.
---@param req nitr.Request
---@return string
function nitr.csrf.token(req) end

---Loads (or starts) the stateless signed-cookie session. Options: `secret` (required), `name` (the cookie name), `max_age`, and `cookie` (the cookie ATTRIBUTES table, which extends the HttpOnly/SameSite=Lax defaults; `http_only` cannot be un-set). Note `nitr.csrf` spells the attribute table `cookie_opts` and uses `cookie` for the name. (std feature: `http`)
---@param req nitr.Request
---@param opts table
---@return nitr.Session
function nitr.session(req, opts) end

---Creates the application object the handler script must return.
---@return nitr.App
function nitr.app() end

---Classifies a pcall-caught error into its structured form: `kind`, `message`, `source`, `line`, `traceback`, `cause`, `pretty`.
---@param caught any
---@return table
function nitr.errinfo(caught) end

---Debug-prints a value (structure included) to the log; returns it unchanged. (std feature: `dbg`)
---@param value any
---@return any
function nitr.dbg(value) end

---An outbound HTTP request (SSRF-guarded, redirect-checked). Options: `headers`, `query`, `json`, `body`, `timeout`, `retry`. Returns an unsent handle. (std feature: `fetch`)
---@param method string
---@param url string
---@param opts? table
---@return nitr.FetchHandle
function nitr.fetch(method, url, opts) end

---Runs fetch handles (and `db:query_async` handles) concurrently; returns their results in order. (std feature: `fetch`)
---@param handles table
---@return table
function nitr.await_all(handles) end

---The minijinja template engine, loading from `[templating] dir`. (std feature: `template`)
nitr.template = {}

---Renders a template.
---@param name string
---@param data? table
---@return string
function nitr.template:render(name, data) end

---The SQLite database (`database` in nitr.toml): WAL, busy timeout, foreign keys on. (std feature: `db`)
nitr.db = {}

---Runs a statement.
---@param sql string
---@param params? table
---@return integer _ Affected row count.
function nitr.db:execute(sql, params) end

---All rows, each a column→value table.
---@param sql string
---@param params? table
---@return table[]
function nitr.db:query(sql, params) end

---The first row, or nil.
---@param sql string
---@param params? table
---@return table|nil
function nitr.db:query_row(sql, params) end

---The first column of the first row.
---@param sql string
---@param params? table
---@return any
function nitr.db:query_one(sql, params) end

---Runs `fn` atomically; rolls back on error. Nestable (savepoints). Use `tx`, not the outer `nitr.db`.
---@param fn fun(tx: nitr.Tx): any
---@return any
function nitr.db:transaction(fn) end

---An unsent query to run alongside fetches.
---@param sql string
---@param params? table
---@param kind? string
---@return table _ A pending handle for `nitr.await_all`.
function nitr.db:query_async(sql, params, kind) end

---Structured logging into the request span. Fields become real keys in JSON log output. (std feature: `log`)
nitr.log = {}

---Debug-level record.
---@param msg string
---@param fields? table
function nitr.log.debug(msg, fields) end

---Info-level record.
---@param msg string
---@param fields? table
function nitr.log.info(msg, fields) end

---Warn-level record.
---@param msg string
---@param fields? table
function nitr.log.warn(msg, fields) end

---Error-level record.
---@param msg string
---@param fields? table
function nitr.log.error(msg, fields) end

---Crypto primitives (RustCrypto): compose them; never reimplement them in Lua. (std feature: `crypto`)
nitr.crypto = {}

---The password cap (1024 bytes): password_hash raises above it, password_verify answers a plain false. Read it to size a registration field — `#pw > nitr.crypto.max_password_bytes` is the pre-check that turns password_hash's error into a 400.
---@type integer
nitr.crypto.max_password_bytes = nil

---SHA-256 digest, lowercase hex.
---@param data string
---@return string
function nitr.crypto.sha256(data) end

---HMAC-SHA256, lowercase hex.
---@param key string
---@param data string
---@return string
function nitr.crypto.hmac_sha256(key, data) end

---N random bytes from the OS (1..=65536).
---@param n integer
---@return string
function nitr.crypto.random_bytes(n) end

---Timing-safe comparison — what `==` on secrets is not.
---@param a string
---@param b string
---@return boolean
function nitr.crypto.constant_time_eq(a, b) end

---argon2id hash for storage (m=19456, t=2, p=1). Also available as `nitr hash-password`. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string At most 1024 bytes; longer is an error, never a silent truncation.
---@return string
function nitr.crypto.password_hash(password) end

---Verifies a password against a stored hash. Total on login input: no password, whatever its size, makes it raise. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string
---@param hash string
---@return boolean _ Whether the password matches.
---@return string|nil _ Set only when the *stored hash* is unusable (bcrypt, truncated, absurd parameters) — nil for an ordinary wrong password, including one over `max_password_bytes` (answered false before argon2 runs, never an error).
function nitr.crypto.password_verify(password, hash) end

---Spends one argon2 hash against a process-private decoy and returns false. Call it on the no-such-user branch of a login: skipping the hash there leaks your user list through response time. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string
---@return boolean _ Always false.
function nitr.crypto.password_verify_dummy(password) end

---Authenticated encryption (XChaCha20-Poly1305); printable token.
---@param key string Exactly 32 bytes.
---@param plaintext string
---@param aad? string
---@return string
function nitr.crypto.seal(key, plaintext, aad) end

---Opens a sealed token; nil on any tampering.
---@param key string
---@param sealed string
---@param aad? string
---@return string|nil
function nitr.crypto.open(key, sealed, aad) end

---HMAC JWTs (HS256/384/512). Verification demands an explicit algorithm allow-list and checks `exp`/`nbf` when present. It does NOT check `iss`, `aud` or `typ` — those are the caller's job — and a token with no `exp` never expires. See docs-feat/jwt.md. (std feature: `crypto`)
nitr.crypto.jwt = {}

---Signs a token.
---@param claims table
---@param key string
---@param opts? table `{ alg = "HS256" }`
---@return string
function nitr.crypto.jwt.sign(claims, key, opts) end

---Verifies the signature, the `alg` against the allow-list, and `exp`/`nbf` if the token carries them. Checks no other claim: compare `iss`/`aud` yourself, and require `exp` if your tokens must expire (`aud` may be a string or an array).
---@param token string
---@param key string
---@param opts table `{ algorithms = {...}, leeway? }` — the allow-list is required.
---@return table|nil _ The claims.
---@return string|nil _ The rejection reason.
function nitr.crypto.jwt.verify(token, key, opts) end

---`Authorization` header parsing. (std feature: `crypto`)
nitr.auth = {}

---Basic credentials, or nil.
---@param req nitr.Request|string
---@return string|nil _ User.
---@return string|nil _ Password.
function nitr.auth.basic(req) end

---The bearer token, or nil.
---@param req nitr.Request|string
---@return string|nil
function nitr.auth.bearer(req) end

---The bounded TTL+LRU cache shared by every state. Entries are plain data; per-process, so not a session store. (std feature: `cache`)
nitr.cache = {}

---The cached value, or nil.
---@param key string
---@return any
function nitr.cache:get(key) end

---Stores a value (ttl in seconds).
---@param key string
---@param value any
---@param ttl? integer
function nitr.cache:set(key, value, ttl) end

---Removes a key.
---@param key string
function nitr.cache:delete(key) end

---Empties the cache.
function nitr.cache:clear() end

---The cached value, or `fn()`'s result, stored and returned.
---@param key string
---@param ttl integer|nil
---@param fn fun(): any
---@return any
function nitr.cache:remember(key, ttl, fn) end

---Hit/miss/entry counters.
---@return table
function nitr.cache:stats() end

---Safe clocks and time formatting (UTC), so scripts never need the `os` library for a date. (std feature: `time`)
nitr.time = {}

---Unix seconds.
---@return integer
function nitr.time.now() end

---Monotonic seconds (sub-second precision), for measuring durations.
---@return number
function nitr.time.monotonic() end

---Formats a timestamp in UTC.
---@param ts integer
---@param fmt? string strftime; default ISO-like.
---@return string
function nitr.time.format(ts, fmt) end

---Parses per a strftime format (UTC unless the input carries an offset).
---@param value string
---@param fmt string
---@return integer|nil
---@return string|nil _ Reason when nil.
function nitr.time.parse(value, fmt) end

---IMF-fixdate (`Tue, 15 Nov 1994 08:12:31 GMT`).
---@param ts integer
---@return string
function nitr.time.http(ts) end

---Parses the three HTTP date forms.
---@param value string
---@return integer|nil
function nitr.time.parse_http(value) end

---RFC 3339 in UTC (`1994-11-15T08:12:31Z`).
---@param ts integer
---@return string
function nitr.time.iso8601(ts) end

---Declarative validation, compiled once and checked in Rust. (std feature: `validate`)
nitr.validate = {}

---Compiles a schema.
---@param fields table `{ name = { type = ..., ... } }` rules; unknown rule keys fail at load.
---@return nitr.Schema
function nitr.validate.schema(fields) end

---Base64 encoding and decoding. (std feature: `base64`)
nitr.base64 = {}

---Encodes bytes.
---@param data string
---@param opts? table `{ url = true }` for the URL-safe alphabet.
---@return string
function nitr.base64.encode(data, opts) end

---Decodes; forgiving about padding, never about the alphabet.
---@param value string
---@param opts? table
---@return string|nil
---@return string|nil _ Reason when nil.
function nitr.base64.decode(value, opts) end

---Lexical path manipulation (POSIX and Windows styles). Pure text: nothing touches the filesystem. (std feature: `path`)
nitr.path = {}

---Joins segments; a later absolute segment never discards the base.
---@param ... string
---@return string
function nitr.path.join(...) end

---The final component.
---@param path string
---@return string
function nitr.path.basename(path) end

---The directory part.
---@param path string
---@return string
function nitr.path.dirname(path) end

---The extension without the dot; nil for none (dotfiles included).
---@param path string
---@return string|nil
function nitr.path.extension(path) end

---Resolves `.`/`..` lexically; `..` cannot climb out of the root. Text-only: before real file access on Windows also reject segments with trailing dots/spaces or colons, which Win32 rewrites.
---@param path string
---@return string
function nitr.path.normalize(path) end

---Whether the path is absolute (`/x`, `C:\x`, UNC).
---@param path string
---@return boolean
function nitr.path.is_absolute(path) end

---Percent-encoding, query strings, and a lexical URL splitter. (std feature: `url`)
nitr.url = {}

---Percent-encodes a component (like `encodeURIComponent`).
---@param value string
---@return string
function nitr.url.encode(value) end

---Percent-decodes (`+` is left alone — that is a form convention).
---@param value string
---@return string
function nitr.url.decode(value) end

---Parses a query string (`+` as space; last duplicate wins).
---@param query string
---@return table<string, string>
function nitr.url.query_parse(query) end

---Builds a query string, keys sorted.
---@param params table
---@return string
function nitr.url.query_build(params) end

---Splits a URL lexically (not a WHATWG parser).
---@param value string
---@return table|nil _ `{ scheme?, userinfo?, host?, port?, path, query?, fragment? }`
---@return string|nil _ Reason when nil.
function nitr.url.parse(value) end

---Read-only environment variable access. Opt-in; reads are filtered by `[env] allow`, and `NITR_*` internals are never visible. Getters only: no setter, no enumeration. (std feature: `env`)
nitr.env = {}

---Reads one variable.
---@param name string
---@param default? string
---@return string|nil _ The value, or the default (nil without one) when unset or not readable.
function nitr.env.get(name, default) end

---Whether the variable is set and readable; a policy-hidden name reports false.
---@param name string
---@return boolean
function nitr.env.has(name) end

---Reads and parses a number; unset or unparseable answers the default.
---@param name string
---@param default? number
---@return number|nil
function nitr.env.number(name, default) end

---Reads a flag: 1/true/yes/on and 0/false/no/off (any case); anything else answers the default.
---@param name string
---@param default? boolean
---@return boolean|nil
function nitr.env.bool(name, default) end

---The `nitr test` framework: available in test files only. (available in `nitr test` files)
nitr.test = {}

---Dispatches through the real router/middleware/handler path.
---@param method string
---@param path string
---@param opts? table `{ headers?, body?, json? }`.
---@return table _ `{ status, headers, body }` plus `:json()`.
function nitr.test.request(method, path, opts) end

---Groups tests; names are prefixed.
---@param name string
---@param fn fun()
function nitr.test.describe(name, fn) end

---One test case.
---@param name string
---@param fn fun()
function nitr.test.it(name, fn) end

---Starts an assertion.
---@param actual any
---@return table _ Matchers: `to_equal`, `to_not_equal`, `to_be_nil`, `to_be_truthy`, `to_match`, `to_contain`.
function nitr.test.expect(actual) end

---Runs before every test in the file.
---@param fn fun()
function nitr.test.before_each(fn) end

---Runs after every test in the file (even failing ones).
---@param fn fun()
function nitr.test.after_each(fn) end

---The configuration snapshot returned by `config.lua` (nil without one). (set when a `config_script` is configured)
nitr.cfg = {}

---User-defined Rust extension modules (`ServerBuilder::module`), one level below the standard library so no future builtin can collide with them. Each module is a table: `nitr.ext.<name>`. Absent until a module is registered.
nitr.ext = {}

