---@meta nitr
-- GENERATED by `nitr` from nitr-api.toml — do not edit by hand.
-- Editor completion for the whole `nitr.*` surface: keep this file
-- next to your scripts (the Lua Language Server picks it up).

---@class nitr
nitr = {}

---The incoming request, passed to every handler and middleware.
---@class nitr.Request
---@field method string Request method, uppercase (`"GET"`).
---@field path string URI path (`"/users/42"`).
---@field params table<string, string> Path parameters captured by the router (`:id` → `params.id`).
---@field query table<string, string> Parsed query string; repeated keys keep the last value.
---@field headers table<string, string> Request headers, lowercase names.
---@field id string The request id (UUIDv7, echoed as `X-Request-ID`).
---@field remote_addr string Peer address (`"ip:port"`).
---@field uri table URI components: `scheme`, `host`, `port`, `path`, `authority`, `query`. An HTTP/1.1 request carries only the path, so `authority`, `host` and `port` come from the client-sent `Host` header (`port` is the scheme's default when it names none) and `scheme` from the listener (`https` under `[tls]`).
---@field cookies nitr.RequestCookies Parsed request cookies.
---@field valid table|nil The route's validated input — `{ body, query, params, headers }` as its `input` declaration coerced, stripped and normalized them; nil on routes without `input`.
local Request = {}

---Reads and decodes the body as JSON. Errors on an empty or invalid body.
---@return table
function Request:json() end

---Reads the whole body as a string.
---@return string
function Request:text() end

---Reads an `application/x-www-form-urlencoded` body as a table. The parse is cached, so middleware and handler can both call it.
---@return table<string, string>
function Request:form() end

---Invokes `fn(part)` once per part of a `multipart/form-data` body, in arrival order; returns the part count. A `[limits]` bound a part crosses (`max_form_parts`, `max_field_bytes`, `max_file_bytes`) raises; uncaught, it answers 413. (Needs the `multipart` Cargo feature.)
---@param fn fun(part: nitr.Part)
---@return integer _ Number of parts seen.
function Request:multipart(fn) end

---Streams the body: the next chunk as it arrives, or at least `n` bytes. `nil` marks the end.
---@param n? integer Minimum bytes to gather.
---@return string|nil
function Request:read(n) end

---The best match among the given media types for the `Accept` header, or nil.
---@param ... string Offered media types.
---@return string|nil
function Request:accepts(...) end

---Whether the client's cached copy is current, per `If-None-Match`/`If-Modified-Since`.
---@param etag? string Entity tag of the current representation.
---@param last_modified? integer Unix seconds of the last change.
---@return boolean
function Request:fresh(etag, last_modified) end

---Cookies from the `Cookie` header: index by name (`req.cookies.session`).
---@class nitr.RequestCookies
local RequestCookies = {}

---The verified value of a signed cookie, or nil when missing or tampered.
---@param name string
---@param secret string
---@return string|nil
function RequestCookies:verify(name, secret) end

---A response: `{ status, headers, body }` plus a cookie builder. Helpers build these; handlers may also build them by hand.
---@class nitr.Response
---@field status integer HTTP status code.
---@field headers table<string, string> Response headers.
---@field body string|fun(...)|nil Body string, or a streaming body function.
---@field cookies nitr.ResponseCookies Set-Cookie builder (attached by the helpers).
local Response = {}

---Builder for `Set-Cookie` headers on a response.
---@class nitr.ResponseCookies
local ResponseCookies = {}

---Adds a cookie. The name must be an RFC 6265 token and the value a cookie-octet string (no whitespace, quotes, commas, semicolons or backslashes — encode with `nitr.base64` or a signed cookie first); anything else raises. Options: `http_only`, `secure`, `path`, `domain`, `max_age` (seconds), `same_site` ("Strict"/"Lax"/"None").
---@param name string
---@param value string
---@param opts? table
function ResponseCookies:set(name, value, opts) end

---Adds an HMAC-signed cookie, verifiable later with `req.cookies:verify`.
---@param name string
---@param value string
---@param secret string
---@param opts? table
function ResponseCookies:set_signed(name, value, secret, opts) end

---The application: routes, middleware, error handling, static mounts. Return it from the handler script.
---@class nitr.App
local App = {}

---Registers a GET route: `middleware..., handler` plus an optional trailing options table `{ input = {...}, doc = {...}, on_invalid = fn, on_error = fn }`. `doc` describes the operation in the OpenAPI document (`summary`, `description`, `tags`, `operation_id`, `responses = { [code] = { description, schema?, content? } }` where `schema` is documentation only, `security = { name }`, `deprecated`, `hidden`); request schemas live under `input`, never `doc`. `input` declares schemas for `body` (a schema, or `{ schema = S, content = { "json", "form", "multipart" } }`, or `{ file = R, content = { "raw" } }`), `query`, `params` and `headers`, enforced in Rust before the handler and exposed as `req.valid`; a failure answers a JSON 422 unless `on_invalid` says otherwise. Paths take `:name` parameters and a trailing `*` catch-all.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:get(path, ...) end

---Registers a POST route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:post(path, ...) end

---Registers a PUT route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:put(path, ...) end

---Registers a DELETE route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:delete(path, ...) end

---Registers a PATCH route (see `get`).
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:patch(path, ...) end

---Registers a HEAD route (see `get`). Without one, HEAD reuses the GET route with the body stripped.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:head(path, ...) end

---Registers an OPTIONS route (see `get`). Without one, OPTIONS answers 204 with `Allow`.
---@param path string
---@param ... fun(req: nitr.Request): nitr.Response|table
function App:options(path, ...) end

---Document-level information for the generated OpenAPI document, once per app: `title`, `version`, `description`, `terms_of_service`, `contact`, `license`, `tags = { { name, description } }`, `security = { name = scheme }` (schemes as OpenAPI security scheme objects, referenced by name from a route's `doc.security`), `external_docs`. Unknown keys fail at load. Needs the `openapi` Cargo feature and `[openapi] enabled = true` to be served; `nitr openapi` generates it regardless.
---@param info table
function App:doc(info) end

---The app-wide answer to a request that failed its route's `input` declaration: `function(err, req)` returning a response, where `err = { code, message, fields, errors }` (`fields` maps each path such as `body.email` to its message; `errors` lists `{ path, part, field, rule, message, params?, label? }`). A route-level `on_invalid` option wins over it.
---@param fn fun(err: table, req: nitr.Request): nitr.Response|table
function App:on_invalid(fn) end

---Adds app-wide middleware: a factory `fn(next) -> fn(req)`. Must be called before any route.
---@param mw fun(next: fun): fun(req: nitr.Request): any
function App:use(mw) end

---Sets the app-wide error handler: `fn(err, req)` where `err` is the structured error (`kind`, `message`, `source`, `line`, `traceback`, ...).
---@param handler fun(err: table, req: nitr.Request): nitr.Response|table
function App:on_error(handler) end

---Mounts a static directory, served in Rust without a Lua state. Routes win: the mount answers a GET or HEAD for a path no route serves with that method. Options: `{ spa = boolean, cache_control = string, dotfiles = boolean }` — dotfiles are hidden unless `dotfiles = true` (`.well-known/` is always served).
---@param mount string
---@param dir string
---@param opts? table
function App:static(mount, dir, opts) end

---One part of a multipart upload, delivered to the `req:multipart` callback.
---@class nitr.Part
---@field name string Form field name (`""` when the part carries none).
---@field filename string|nil Client-supplied file name, raw; nil for an ordinary field.
---@field safe_filename string|nil `filename` reduced to a single safe path segment; nil exactly when `filename` is.
---@field content_type string|nil Part content type.
local Part = {}

---Reads a non-file field as a string (bounded by `[limits] max_field_bytes`).
---@return string
function Part:text() end

---Streams a file part to `path` without entering the Lua heap; returns the bytes written. An existing file at `path` is replaced only once the whole part is written.
---@param path string
---@return integer
function Part:save(path) end

---Drains and drops the part; returns the bytes skipped.
---@return integer
function Part:discard() end

---An unsent outbound request from `nitr.fetch`; send it, or hand it to `nitr.await_all`.
---@class nitr.FetchHandle
local FetchHandle = {}

---Performs the request.
---@return nitr.FetchResponse
function FetchHandle:send() end

---An outbound response.
---@class nitr.FetchResponse
---@field status integer HTTP status code.
---@field headers table<string, string> Response headers, lowercase names: the last value of a repeated one, as the bytes the upstream sent.
---@field raw_headers table[] `{ name, value }` pairs in order, repeats included (every `Set-Cookie`).
---@field url string Final URL after redirects.
local FetchResponse = {}

---The body as a string (bounded by `[fetch] max_response_bytes`).
---@return string
function FetchResponse:text() end

---The body decoded as JSON.
---@return table
function FetchResponse:json() end

---Streams the body chunk by chunk; `nil` at the end.
---@return string|nil
function FetchResponse:read() end

---A compiled validation schema from `nitr.validate.schema`.
---@class nitr.Schema
local Schema = {}

---Validates a value. Returns the data (declared fields only, transformed) or nil plus `{ code, message, fields, errors }`: `fields` maps each failing path (`email`, `home.city`, `tags[2]`) to its message, `errors` lists `{ path, field, rule, message, params?, label? }`. Custom `check`s run in the caller's coroutine.
---@param value any
---@return table|nil _ Validated data.
---@return table|nil _ The error, when validation failed.
function Schema:check(value) end

---A copy with every top-level field optional and no defaults filled in — the PATCH body of a POST schema, which must not reset what it omits.
---@return nitr.Schema
function Schema:partial() end

---A copy keeping only the named fields.
---@param names string[]
---@return nitr.Schema
function Schema:pick(names) end

---A copy without the named fields. A cross-field rule naming a dropped field fails at load.
---@param names string[]
---@return nitr.Schema
function Schema:omit(names) end

---A copy with fields added or replaced; `false` removes one.
---@param fields table
---@return nitr.Schema
function Schema:extend(fields) end

---A copy with different options (`title`, `strict`, `messages`, the cross-field groups, `checks`).
---@param opts table
---@return nitr.Schema
function Schema:with(opts) end

---The declared field names, sorted.
---@return string[]
function Schema:fields() end

---A validated upload from a route's `file` rule: the bytes are spooled under `[multipart] upload_dir` and never enter the Lua heap. A file neither saved nor discarded is removed when the request ends.
---@class nitr.File
---@field filename string|nil The client's file name, raw (display text, never a path).
---@field safe_filename string|nil The name reduced to one safe path segment.
---@field extension string|nil The lowercase last suffix of `safe_filename`.
---@field content_type string The media type as detected from the bytes (the declared header only where nothing is detectable).
---@field size integer Bytes received.
---@field width integer|nil Image width from the header (png, jpeg, gif, webp, bmp, tiff).
---@field height integer|nil Image height from the header.
local File = {}

---Moves the file to `rel` inside `[multipart] upload_dir` (never outside it) and returns the path.
---@param rel string
---@return string
function File:save(rel) end

---The contents as a string, only for a file within `[limits] max_field_bytes`.
---@return string
function File:text() end

---A hex digest streamed from disk (`sha256`, the default and only algorithm today).
---@param algo? string
---@return string
function File:hash(algo) end

---Removes the spooled file now.
function File:discard() end

---A stateless signed-cookie session from `nitr.session`. Assign fields directly (`session.user_id = 42`).
---@class nitr.Session
local Session = {}

---Serializes the session into a signed cookie on the response. An empty session deletes the cookie.
---@param resp nitr.Response|table
function Session:save(resp) end

---Removes every field; `save` then writes the deletion cookie.
function Session:clear() end

---A database transaction handle inside `nitr.db:transaction`; same query API as `nitr.db`, plus nesting via savepoints.
---@class nitr.Tx
local Tx = {}

---A response from `t.request`.
---@class nitr.test.Response
---@field status integer The status code.
---@field headers table<string, string> Lowercase name → last value (call it as `resp:headers(name)` for every value).
---@field raw_headers table[] `{ name, value }` pairs in order, repeats included.
---@field body string The whole body (streams are collected).
---@field cookies table<string, table> Name → `{ value, path, domain, max_age, expires, secure, http_only, same_site }` from every `Set-Cookie`.
---@field error table|nil When the handler raised: the table `on_error` receives (`kind`, `message`, `source`, `line`, `traceback`, ...) plus `handled` (true when `on_error` answered). The bytes sent to a client never carry it.
local Response = {}

---The body decoded as JSON; raises when it does not decode.
---@return any
function Response:json() end

---The body as a string.
---@return string
function Response:text() end

---The first value of a header, or nil.
---@param name string
---@return string|nil
function Response:header(name) end

---The body parsed as a `text/event-stream`: `{ event?, data, id?, retry? }` per dispatched event (`id`/`retry` as the event carried them).
---@return table[]
function Response:sse() end

---A client from `t.client`: `:request(method, path, opts)` and `:get`/`:post`/`:put`/`:patch`/`:delete`/`:head`/`:options`.
---@class nitr.test.Client
---@field jar nitr.test.Jar|nil The cookie jar, with `cookies = true`.
local Client = {}

---A request with the client's defaults and jar.
---@param method string
---@param path string
---@param opts? table
---@return nitr.test.Response
function Client:request(method, path, opts) end

---A client's cookie jar.
---@class nitr.test.Jar
local Jar = {}

---The stored cookie `{ name, value, path, domain?, secure?, http_only?, same_site?, expires_at? }`, or nil once deleted or expired.
---@param name string
---@return table|nil
function Jar:get(name) end

---Stores a cookie as if the server had set it (a forged or signed one).
---@param name string
---@param value string
---@param opts? table `{ path? }`
function Jar:set(name, value, opts) end

---Forgets every cookie.
function Jar:clear() end

---The application compiled into the test state (`t.app()`), for unit tests. `dispatch` runs the composed middleware chain only: route `input` validation, `on_invalid`, `on_error` and the protection layer are what `t.request` exercises.
---@class nitr.test.App
local App = {}

---A route's own handler function, without its middleware: by the pattern as registered (`"/notes/:id"`) or a path the router matches.
---@param method string
---@param path string
---@return fun(req: nitr.Request): table
function App:handler(method, path) end

---The server's router lookup (params filled into `req`, `HEAD` falling back to `GET`) and the composed middleware chain; a `404`/`405`/`OPTIONS` answer for what the router does not match.
---@param method string
---@param path string
---@param req nitr.Request
---@return table
function App:dispatch(method, path, req) end

---`{ method, path, file, line }` per route, in registration order.
---@return table[]
function App:routes() end

---As a function: a JSON response (`nitr.json({ ok = true })`). Also the codec: `nitr.json:encode(v)` / `nitr.json:decode(s)`. A table whose keys are `1..n` (holes as `null`) is an array; one mixing list items and named keys has no JSON shape and raises, here and wherever a value is serialized (cache, session, JWT, templates). (std feature: `json`)
---@class nitr.json
---@overload fun(value: any, status: integer?): nitr.Response
nitr.json = {}

---Encodes a value as JSON.
---@param value any
---@return string
function nitr.json:encode(value) end

---Decodes JSON; errors on invalid input.
---@param s string
---@return any
function nitr.json:decode(s) end

---A `text/plain` response. (std feature: `http`)
---@param body string
---@param status? integer
---@return nitr.Response
function nitr.text(body, status) end

---A `text/html` response. (std feature: `http`)
---@param body string
---@param status? integer
---@return nitr.Response
function nitr.html(body, status) end

---A redirect (default 302). (std feature: `http`)
---@param location string
---@param status? integer
---@return nitr.Response
function nitr.redirect(location, status) end

---An empty response with the given status. (std feature: `http`)
---@param code integer
---@return nitr.Response
function nitr.status(code) end

---Picks the offer whose media type best matches the `Accept` header; function values are called with the request. No match answers 406. Offers are a list `{ { type, value }, ... }`, where a tie goes to the earlier entry, or a map `{ [type] = value }`, where it goes to the type that sorts first. (std feature: `http`)
---@param req nitr.Request
---@param offers table
---@return any
function nitr.negotiate(req, offers) end

---A Server-Sent Events stream: `fn(send)` calls `send(event, data)`; table data is JSON-encoded. (std feature: `http`)
---@param fn fun(send: fun(event: string, data: any))
---@return nitr.Response
function nitr.sse(fn) end

---An error response: string body as text, table body as JSON. (std feature: `http`)
---@param code integer
---@param body string|table|nil
---@return nitr.Response
function nitr.error(code, body) end

---A well-formed entity tag for whatever identifies the resource (a row version, an updated_at), to pair with `req:fresh`. (std feature: `http`)
---@param value any
---@param weak? boolean
---@return string
function nitr.etag(value, weak) end

---As a function: the CSRF middleware factory for `app:use` (signed double-submit cookie; unsafe methods must echo the token in `X-CSRF-Token` or a `_csrf` field). Options: `secret` (required), `cookie` (the cookie NAME, default `_csrf`), `header`, `field`, and `cookie_opts` (the cookie ATTRIBUTES, which extend the HttpOnly/SameSite=Lax defaults rather than replacing them; `http_only` cannot be un-set). Note `nitr.session` spells its attribute table `cookie` — here that key is the name. Unsafe requests a browser marks `Sec-Fetch-Site: cross-site` are refused before the token is checked, unless `cookie_opts.same_site = "None"` (the setting that means to accept cross-site posts). (std feature: `http`)
---@class nitr.csrf
---@overload fun(opts: table): fun
nitr.csrf = {}

---The request's token, for a form or meta tag. Requires the middleware.
---@param req nitr.Request
---@return string
function nitr.csrf.token(req) end

---Loads (or starts) the stateless signed-cookie session. Options: `secret` (required), `name` (the cookie name), `max_age`, and `cookie` (the cookie ATTRIBUTES table, which extends the HttpOnly/SameSite=Lax defaults; `http_only` cannot be un-set). Note `nitr.csrf` spells the attribute table `cookie_opts` and uses `cookie` for the name. (std feature: `http`)
---@param req nitr.Request
---@param opts table
---@return nitr.Session
function nitr.session(req, opts) end

---Creates the application object the handler script must return.
---@return nitr.App
function nitr.app() end

---Classifies a pcall-caught error into its structured form: `kind`, `message`, `source`, `line`, `traceback`, `cause`, `pretty`.
---@param caught any
---@return table
function nitr.errinfo(caught) end

---Debug-prints a value (structure included) to the log; returns it unchanged. (std feature: `dbg`)
---@param value any
---@return any
function nitr.dbg(value) end

---An outbound HTTP request (SSRF-guarded, redirect-checked). Options: `headers`, `query`, `json`, `body`, `timeout`, `retry`. Returns an unsent handle. `retry = { attempts, backoff }` repeats an idempotent request after a network failure or a retryable status, never after a refusal by the `[fetch]` policy. (std feature: `fetch`)
---@param method string
---@param url string
---@param opts? table
---@return nitr.FetchHandle
function nitr.fetch(method, url, opts) end

---Runs fetch handles (and `db:query_async` handles) concurrently, passed as separate arguments (`nitr.await_all(h1, h2)`), and returns their results as multiple values in the same order. At most `[fetch] max_concurrent` run at a time; the rest wait their turn. (std feature: `fetch`)
---@param ... nitr.FetchHandle|table
---@return ...
function nitr.await_all(...) end

---The current test's captured log entries, `{ level, target, message, fields?, request_id? }` each (`nitr.log` fields decoded), including `debug` from `nitr.log` whatever the console level. Needs `[testing] capture` (the default); a failed test prints its entries. (available in `nitr test` files)
---@class nitr.test.logs
---@overload fun(): table[]
nitr.test.logs = {}

---Drops the entries captured so far.
function nitr.test.logs.clear() end

---The minijinja template engine, loading from `[templating] dir`. (std feature: `template`)
nitr.template = {}

---Renders a template. HTML auto-escaping is on unless the name (before any `.j2`) ends in a plain-text extension (`.txt`, `.md`, `.csv`, `.json`, `.yaml`, `.toml`). Loading and rendering happen off the async worker.
---@param name string
---@param data? table
---@return string
function nitr.template:render(name, data) end

---The SQLite database (`database` in nitr.toml): WAL, busy timeout, foreign keys on. A row is a column→value table, so a query whose result columns share a name raises (alias one with `AS`). (std feature: `db`)
nitr.db = {}

---Runs a statement.
---@param sql string
---@param params? table Positional values; `nil` (anywhere, trailing included) and JSON `null` bind NULL. A table from `table.pack` counts to its `n`, which is also how a lone NULL is passed (`{ n = 1 }`): an empty list is not padded, so a statement called without its parameters fails.
---@return integer _ Affected row count.
function nitr.db:execute(sql, params) end

---All rows, each a column→value table. A result larger than `[database] max_rows` (default 10000) raises rather than truncating.
---@param sql string
---@param params? table
---@return table[]
function nitr.db:query(sql, params) end

---The first row as a column→value table, or nil when the query returns no rows.
---@param sql string
---@param params? table
---@return table|nil
function nitr.db:query_row(sql, params) end

---The row of a query that must return exactly one row (a column→value table); raises when it returns none or more than one.
---@param sql string
---@param params? table
---@return table
function nitr.db:query_one(sql, params) end

---Runs `fn` atomically; rolls back on error. Nestable (savepoints). Use `tx`, not the outer `nitr.db`.
---@param fn fun(tx: nitr.Tx): any
---@return any
function nitr.db:transaction(fn) end

---An unsent query to run alongside fetches.
---@param sql string
---@param params? table
---@param kind? string
---@return table _ A pending handle for `nitr.await_all`.
function nitr.db:query_async(sql, params, kind) end

---Structured logging into the request span. Fields become real keys in JSON log output. (std feature: `log`)
nitr.log = {}

---Debug-level record.
---@param msg string
---@param fields? table
function nitr.log.debug(msg, fields) end

---Info-level record.
---@param msg string
---@param fields? table
function nitr.log.info(msg, fields) end

---Warn-level record.
---@param msg string
---@param fields? table
function nitr.log.warn(msg, fields) end

---Error-level record.
---@param msg string
---@param fields? table
function nitr.log.error(msg, fields) end

---Crypto primitives (RustCrypto): compose them; never reimplement them in Lua. (std feature: `crypto`)
nitr.crypto = {}

---The password cap (1024 bytes): password_hash raises above it, password_verify answers a plain false. Read it to size a registration field — `#pw > nitr.crypto.max_password_bytes` is the pre-check that turns password_hash's error into a 400.
---@type integer
nitr.crypto.max_password_bytes = nil

---SHA-256 digest, lowercase hex.
---@param data string
---@return string
function nitr.crypto.sha256(data) end

---HMAC-SHA256, lowercase hex.
---@param key string
---@param data string
---@return string
function nitr.crypto.hmac_sha256(key, data) end

---N random bytes from the OS (1..=65536).
---@param n integer
---@return string
function nitr.crypto.random_bytes(n) end

---Timing-safe comparison — what `==` on secrets is not.
---@param a string
---@param b string
---@return boolean
function nitr.crypto.constant_time_eq(a, b) end

---argon2id hash for storage (m=19456, t=2, p=1). Also available as `nitr hash-password`. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string At most 1024 bytes; longer is an error, never a silent truncation.
---@return string
function nitr.crypto.password_hash(password) end

---Verifies a password against a stored hash. Total on login input: no password, whatever its size, makes it raise. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string
---@param hash string
---@return boolean _ Whether the password matches.
---@return string|nil _ Set only when the *stored hash* is unusable (bcrypt, truncated, absurd parameters) — nil for an ordinary wrong password, including one over `max_password_bytes` (answered false before argon2 runs, never an error).
function nitr.crypto.password_verify(password, hash) end

---Spends one argon2 hash against a process-private decoy and returns false. Call it on the no-such-user branch of a login: skipping the hash there leaks your user list through response time. ASYNC: the argon2 work runs on the blocking pool, so this yields — call it from a handler or middleware, never from the top level of a handler script (that chunk runs outside the async executor and a yield there fails). Store hashes minted by `nitr hash-password` instead of hashing at boot.
---@param password string
---@return boolean _ Always false.
function nitr.crypto.password_verify_dummy(password) end

---Authenticated encryption (XChaCha20-Poly1305); printable token.
---@param key string Exactly 32 bytes.
---@param plaintext string
---@param aad? string
---@return string
function nitr.crypto.seal(key, plaintext, aad) end

---Opens a sealed token; nil on any tampering.
---@param key string
---@param sealed string
---@param aad? string
---@return string|nil
function nitr.crypto.open(key, sealed, aad) end

---HMAC JWTs (HS256/384/512). Verification demands an explicit algorithm allow-list and checks `exp`/`nbf` when present. It does NOT check `iss`, `aud` or `typ` — those are the caller's job — and a token with no `exp` never expires. See docs-feat/jwt.md. (std feature: `crypto`)
nitr.crypto.jwt = {}

---Signs a token.
---@param claims table
---@param key string
---@param opts? table `{ alg = "HS256" }`
---@return string
function nitr.crypto.jwt.sign(claims, key, opts) end

---Verifies the signature, the `alg` against the allow-list, and `exp`/`nbf` if the token carries them. Checks no other claim: compare `iss`/`aud` yourself, and require `exp` if your tokens must expire (`aud` may be a string or an array).
---@param token string
---@param key string
---@param opts table `{ algorithms = {...}, leeway? }` — the allow-list is required.
---@return table|nil _ The claims.
---@return string|nil _ The rejection reason.
function nitr.crypto.jwt.verify(token, key, opts) end

---`Authorization` header parsing. (std feature: `crypto`)
nitr.auth = {}

---Basic credentials, or nil. Credentials must be UTF-8, and the scheme must be separated from the value by at least one space (extra spaces are trimmed; a tab is not a separator). Anything unparseable reads as no credentials, never a partial one.
---@param req nitr.Request|string
---@return string|nil _ User.
---@return string|nil _ Password.
function nitr.auth.basic(req) end

---The bearer token, or nil. Compare it with nitr.crypto.constant_time_eq, not ==; a length mismatch still returns early, so a variable-length secret is compared as a digest. See examples/bearer-auth.
---@param req nitr.Request|string
---@return string|nil
function nitr.auth.bearer(req) end

---The bounded TTL+LRU cache shared by every state. Entries are plain data; per-process, so not a session store. (std feature: `cache`)
nitr.cache = {}

---The cached value, or nil.
---@param key string
---@return any
function nitr.cache:get(key) end

---Stores a value; `opts` is `{ ttl = seconds }` (`0` never expires, as `[cache] default_ttl`). Setting `nil` removes the key.
---@param key string
---@param value any
---@param opts? table
function nitr.cache:set(key, value, opts) end

---Removes a key; whether it was there.
---@param key string
---@return boolean
function nitr.cache:delete(key) end

---Empties the cache.
function nitr.cache:clear() end

---The cached value, or `fn()`'s result, stored and returned. Call as `remember(key, fn)` or `remember(key, { ttl = seconds }, fn)`.
---@param key string
---@param opts table|fun(): any
---@param fn fun(): any|nil
---@return any
function nitr.cache:remember(key, opts, fn) end

---Hit/miss/entry counters.
---@return table
function nitr.cache:stats() end

---Safe clocks and time formatting (UTC), so scripts never need the `os` library for a date. (std feature: `time`)
nitr.time = {}

---Unix seconds.
---@return integer
function nitr.time.now() end

---Monotonic seconds (sub-second precision), for measuring durations.
---@return number
function nitr.time.monotonic() end

---Formats a timestamp in UTC.
---@param ts integer
---@param fmt? string strftime; default ISO-like.
---@return string
function nitr.time.format(ts, fmt) end

---Parses per a strftime format (UTC unless the input carries an offset).
---@param value string
---@param fmt string
---@return integer|nil
---@return string|nil _ Reason when nil.
function nitr.time.parse(value, fmt) end

---IMF-fixdate (`Tue, 15 Nov 1994 08:12:31 GMT`).
---@param ts integer
---@return string
function nitr.time.http(ts) end

---Parses the three HTTP date forms.
---@param value string
---@return integer|nil
function nitr.time.parse_http(value) end

---RFC 3339 in UTC (`1994-11-15T08:12:31Z`).
---@param ts integer
---@return string
function nitr.time.iso8601(ts) end

---Declarative validation, compiled once and checked in Rust. Rules are tables (`{ type = "string", min_len = 1 }`), shorthand strings (`"string|trim|min_len:1|required"`), the mixed form (`{ "string|required", message = "..." }`) or compiled schemas. Types: string, integer, number, boolean, array, table, map, any, file. Every rule has a default message; `message`/`messages` override per field, schema options `messages` per schema, `nitr.validate.messages` per app, with `{min}`-style placeholders (never `{value}`). (std feature: `validate`)
nitr.validate = {}

---Compiles a schema.
---@param fields table `{ name = rule, ... }`; unknown rule keys fail at load.
---@param opts? table `title`, `strict`, `messages`, `at_least_one`, `mutually_exclusive`, `dependent_required`, `equal_fields`, `ordered`, `checks = { { description, check = fn(data) } }`.
---@return nitr.Schema
function nitr.validate.schema(fields, opts) end

---Registers a custom string format usable as `format = name`. Per state, before the schemas that use it; built-in names and duplicates fail.
---@param name string
---@param spec table `{ description, check = fn(s), message?, pattern?, example? }`; `pattern` is documentation only.
function nitr.validate.format(name, spec) end

---Every format name, built in and custom, sorted.
---@return string[]
function nitr.validate.formats() end

---App-wide default messages per rule code. At load only; a call after the application compiled raises.
---@param messages table `{ rule = "template", summary = "..." }`.
function nitr.validate.messages(messages) end

---The table form of a shorthand rule string.
---@param shorthand string
---@return table
function nitr.validate.expand(shorthand) end

---The media types a `file` rule may name: `{ ["image/png"] = { extensions, family, tier, dimensions } }`.
---@return table
function nitr.validate.media_types() end

---A `file` rule preset: png, jpeg, gif, webp, bmp; `max_bytes = "5mb"`, `max_pixels = 25000000`. `opts` overrides any key.
---@param opts? table
---@return table
function nitr.validate.image(opts) end

---A `file` rule preset: pdf, docx, xlsx, pptx, odt, ods, odp, rtf; `max_bytes = "20mb"`.
---@param opts? table
---@return table
function nitr.validate.document(opts) end

---A `file` rule preset: xlsx, ods, csv; `max_bytes = "20mb"`.
---@param opts? table
---@return table
function nitr.validate.spreadsheet(opts) end

---A `file` rule preset: txt, csv, md, json, xml, yaml; UTF-8 required; `max_bytes = "1mb"`.
---@param opts? table
---@return table
function nitr.validate.text_file(opts) end

---A `file` rule preset: zip, gzip, tar, bz2, xz, zstd, 7z; `max_bytes = "50mb"`.
---@param opts? table
---@return table
function nitr.validate.archive(opts) end

---A `file` rule preset: mp3, wav, ogg, flac, m4a; `max_bytes = "50mb"`.
---@param opts? table
---@return table
function nitr.validate.audio(opts) end

---A `file` rule preset: mp4, mov, webm, mkv; `max_bytes = "500mb"` (above the default `[limits] max_file_bytes`, which still caps it).
---@param opts? table
---@return table
function nitr.validate.video(opts) end

---A `file` rule preset: woff, woff2, ttf, otf; `max_bytes = "5mb"`.
---@param opts? table
---@return table
function nitr.validate.font(opts) end

---A `file` rule accepting any type; executables are still refused.
---@param opts table `max_bytes` required.
---@return table
function nitr.validate.any_file(opts) end

---Base64 encoding and decoding. (std feature: `base64`)
nitr.base64 = {}

---Encodes bytes.
---@param data string
---@param opts? table `{ url = true }` for the URL-safe alphabet.
---@return string
function nitr.base64.encode(data, opts) end

---Decodes; forgiving about padding, never about the alphabet.
---@param value string
---@param opts? table
---@return string|nil
---@return string|nil _ Reason when nil.
function nitr.base64.decode(value, opts) end

---Lexical path manipulation (POSIX and Windows styles). Pure text: nothing touches the filesystem. (std feature: `path`)
nitr.path = {}

---Joins segments; a later absolute segment never discards the base.
---@param ... string
---@return string
function nitr.path.join(...) end

---The final component.
---@param path string
---@return string
function nitr.path.basename(path) end

---The directory part.
---@param path string
---@return string
function nitr.path.dirname(path) end

---The extension without the dot; nil for none (dotfiles included).
---@param path string
---@return string|nil
function nitr.path.extension(path) end

---Resolves `.`/`..` lexically; `..` cannot climb out of the root. Text-only: before real file access on Windows also reject segments with trailing dots/spaces or colons, which Win32 rewrites.
---@param path string
---@return string
function nitr.path.normalize(path) end

---Whether the path is absolute (`/x`, `C:\x`, UNC).
---@param path string
---@return boolean
function nitr.path.is_absolute(path) end

---Percent-encoding, query strings, and a lexical URL splitter. (std feature: `url`)
nitr.url = {}

---Percent-encodes a component (like `encodeURIComponent`).
---@param value string
---@return string
function nitr.url.encode(value) end

---Percent-decodes (`+` is left alone — that is a form convention).
---@param value string
---@return string
function nitr.url.decode(value) end

---Parses a query string (`+` as space; last duplicate wins).
---@param query string
---@return table<string, string>
function nitr.url.query_parse(query) end

---Builds a query string, keys sorted.
---@param params table
---@return string
function nitr.url.query_build(params) end

---Splits a URL lexically (not a WHATWG parser).
---@param value string
---@return table|nil _ `{ scheme?, userinfo?, host?, port?, path, query?, fragment? }`
---@return string|nil _ Reason when nil.
function nitr.url.parse(value) end

---Read-only environment variable access. Opt-in; reads are filtered by `[env] allow`, and `NITR_*` internals are never visible. Getters only: no setter, no enumeration. (std feature: `env`)
nitr.env = {}

---Reads one variable.
---@param name string
---@param default? string
---@return string|nil _ The value, or the default (nil without one) when unset or not readable.
function nitr.env.get(name, default) end

---Whether the variable is set and readable; a policy-hidden name reports false.
---@param name string
---@return boolean
function nitr.env.has(name) end

---Reads and parses a number; unset or unparseable answers the default.
---@param name string
---@param default? number
---@return number|nil
function nitr.env.number(name, default) end

---Reads a flag: 1/true/yes/on and 0/false/no/off (any case); empty means false, anything else answers the default.
---@param name string
---@param default? boolean
---@return boolean|nil
function nitr.env.bool(name, default) end

---HMAC-SHA256 cookie signing, the same as `res.cookies:set_signed` and `req.cookies:verify` use — for a signed value that travels outside a cookie header, or a test that forges one. (std feature: `http`)
nitr.cookie = {}

---`b64(value).b64(hmac)`, the cookie name bound into the MAC so a value cannot move between cookies.
---@param name string
---@param value string
---@param secret string
---@return string
function nitr.cookie.sign(name, value, secret) end

---The value, or nil when the signature does not match (constant-time comparison).
---@param name string
---@param signed string
---@param secret string
---@return string|nil
function nitr.cookie.verify(name, signed, secret) end

---The `nitr test` framework: available in test files only, never in a state that serves requests. A file registers tests; the runner then runs each with its own budget, timeout, duration, captured logs and fresh doubles. Doubles are per test: set them in the test or in `before_each`. (available in `nitr test` files)
nitr.test = {}

---Dispatches through the real protection/router/middleware/handler path, as a request from a client would.
---@param method string
---@param path string
---@param opts? table `{ headers?, query?, cookies?, auth?, body? | json? | form? | multipart?, remote_addr?, timeout? }`: `query` is appended (a list repeats the key); `cookies` becomes one `cookie:` header; `auth` is `{ bearer = token }` or `{ basic = { user, password } }`; exactly one body option (two is an error), and `json`/`form`/`multipart` set `content-type` only when the caller did not; `remote_addr` is the peer the server sees (default `127.0.0.1`), which `[rate_limit]` keys by; `timeout` (seconds, default `[lua] exec_timeout_ms`) bounds the whole exchange, so an endless stream fails the test instead of hanging the run.
---@return nitr.test.Response
function nitr.test.request(method, path, opts) end

---`t.request("GET", ...)`. Also `post`, `put`, `patch`, `delete`, `head`, `options`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.get(path, opts) end

---`t.request("POST", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.post(path, opts) end

---`t.request("PUT", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.put(path, opts) end

---`t.request("PATCH", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.patch(path, opts) end

---`t.request("DELETE", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.delete(path, opts) end

---`t.request("HEAD", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.head(path, opts) end

---`t.request("OPTIONS", ...)`.
---@param path string
---@param opts? table
---@return nitr.test.Response
function nitr.test.options(path, opts) end

---A client with defaults and, with `cookies = true`, a jar: cookies stored by name and path (a `Set-Cookie` without `Path` gets the RFC 6265 default, the request path's directory), `Max-Age=0` and a past `Expires` delete, expiry follows `t.clock`. `Secure` and `Domain` are stored and reported but not enforced (there is no transport and one host).
---@param opts? table `{ base?, headers?, cookies = true?, remote_addr? }`: a path prefix, headers merged under every call's, a cookie jar, the peer address.
---@return nitr.test.Client
function nitr.test.client(opts) end

---Groups tests: names are prefixed and hooks registered inside apply to the group. The body runs protected: a throw fails the tests it registered so far plus one `<name> (describe body)` failure, and the file carries on.
---@param name string
---@param fn fun()
function nitr.test.describe(name, fn) end

---Registers one test.
---@param name string
---@param fn fun()
function nitr.test.it(name, fn) end

---Registers a skipped test (reported apart from `--filter`'s filtered-out tests).
---@param name string
---@param fn_or_reason? fun()|string
function nitr.test.skip(name, fn_or_reason) end

---A test not written yet; `--list` shows it.
---@param name string
function nitr.test.todo(name) end

---Focuses the file: its other tests are skipped (reason `only`). The run exits 1 while any `only` is left in place.
---@param name string
---@param fn fun()
function nitr.test.only(name, fn) end

---`t.each(cases)(name, fn)`: one test per case. A positional case (a list) is `string.format`ted into `name` and unpacked into `fn`; a named case (a table with string keys) is passed whole and `name` formats its `name` field.
---@param cases table[]
---@return fun(name: string, fn: fun(...))
function nitr.test.each(cases) end

---Fails the current test from anywhere.
---@param message? string
function nitr.test.fail(message) end

---Starts an assertion.
---@param actual any
---@return table _ Matchers: `to_equal`, `to_not_equal`, `to_be_nil`, `to_not_be_nil`, `to_be_truthy`, `to_be_false`, `to_be_a(type)` (`"integer"`/`"float"` via `math.type`), `to_have_length`, `to_be_greater_than`, `to_be_greater_than_or_equal`, `to_be_less_than`, `to_be_less_than_or_equal`, `to_have_key`, `to_match_object(subset)` (recursive; extra keys ignored), `to_match(pattern)`, `to_not_match`, `to_contain`, `to_not_contain`, `to_throw(text?)` (plain substring of the message), `to_not_throw`, `to_contain_log(subset)`; on a response (from `t.request`, or a table a handler returned): `to_have_status(n)` (a failure shows a body excerpt and `resp.error`), `to_have_header(name, value_or_pattern?)`, `to_have_json(subset)`. Values render bounded (40 entries, 256 bytes).
function nitr.test.expect(actual) end

---Runs before every test registered after it in this group (and nested ones), outer groups first.
---@param fn fun()
function nitr.test.before_each(fn) end

---Runs after every test registered after it in this group, inner groups first, even when the test failed; its own failure fails a test that passed.
---@param fn fun()
function nitr.test.after_each(fn) end

---Runs once before the group's first test that runs (inside that test's budget). A group left with no test to run runs neither `before_all` nor `after_all`.
---@param fn fun()
function nitr.test.before_all(fn) end

---Runs once after the group's last test that runs.
---@param fn fun()
function nitr.test.after_all(fn) end

---A real request object for a unit test: `req.*`, `req:json()`, `nitr.session(req, ...)`, `nitr.csrf.token(req)` and `nitr.auth.*` work on it. It passes no protection layer, no body guard and no route validation (`valid` is what the spec says), and multipart parts cannot `:save()`.
---@param spec? table `{ method?, path?, params?, valid?, ... }` plus every `t.request` option.
---@return nitr.Request
function nitr.test.fake_request(spec) end

---The application compiled into this test state (once per file): its handler script's top level and every `app:use` factory run once more here, and nothing it registers is served.
---@return nitr.test.App
function nitr.test.app() end

---Exactly the value `session:save` would write for `data`, for a client's jar: `api.jar:set("session", t.session_cookie({ user = "ann" }, { secret = nitr.cfg.session_secret }))`.
---@param data table
---@param opts table `{ secret, name?, max_age? }`
---@return string
function nitr.test.session_cookie(data, opts) end

---Canned responses for `nitr.fetch` in the handlers under test, answered in Rust before the `[fetch]` policy and the resolver: a matched rule never leaves the process (so a test can mock an internal host without widening `[fetch]`), an unmatched request goes out unchanged, policy included. A mocked call still counts against `max_per_request`; a canned `3xx` is returned as is and `retry` is not exercised. Reset before every test. (available in `nitr test` files)
nitr.test.fetch = {}

---Adds rules; the first one that matches (method, URL, uses left) answers.
---@param ... table `{ url, method?, status?, headers?, json? | body?, times? }`: `url` exact, or a prefix written with a trailing `*`; `json` sets `content-type`; `times` spends the rule.
function nitr.test.fetch.mock(...) end

---With strict on (the default argument), a request no rule matches raises `no fetch mock matched ...` instead of going out.
---@param on? boolean
function nitr.test.fetch.strict(on) end

---Every outbound call made since the test started, answered or not.
---@return table[] _ `{ method, url, headers, body?, json?, mocked }` per call, oldest first (at most 10 000).
function nitr.test.fetch.calls() end

---Drops the rules, the recorded calls and the strict flag.
function nitr.test.fetch.reset() end

---The standard library's clock — `nitr.time`, session and JWT expiry, the `after`/`before` validation rules, cache TTLs, the rate limiter's window — but never the execution budget or any timeout. Reset after every test. (available in `nitr test` files)
nitr.test.clock = {}

---Freezes the wall clock at `ts` (elapsed time keeps flowing).
---@param ts number Unix seconds.
function nitr.test.clock.set(ts) end

---Moves wall and elapsed time forward together (at most a century in total).
---@param secs number
function nitr.test.clock.advance(secs) end

---Back to the real clock.
function nitr.test.clock.reset() end

---The clock's unix seconds.
---@return integer
function nitr.test.clock.now() end

---Overrides for `nitr.env`, applied after the `[env]` policy: a name the policy hides stays hidden. Reset before every test. (available in `nitr test` files)
nitr.test.env = {}

---Makes `nitr.env.get(name)` answer `value`.
---@param name string
---@param value string
function nitr.test.env.set(name, value) end

---Makes the variable read as unset.
---@param name string
function nitr.test.env.unset(name) end

---Drops every override.
function nitr.test.env.reset() end

---Fixtures over the test database (never `[database] path`: a scratch file, or `[testing] database`). Every Lua state owns its connection, so the transaction-and-rollback trick cannot work here; a snapshot taken after the migrations, the configuration script and `[testing] seed` is restored instead. The file is created fresh for every run. (available in `nitr test` files)
nitr.test.db = {}

---Restores the post-migration (+ seed) snapshot. A connection holding a write lock past `[database] busy_timeout` fails it with an error naming the cause.
function nitr.test.db.reset() end

---Empties the named tables (every application table without an argument) in one transaction, foreign keys checked at commit, `AUTOINCREMENT` counters reset.
---@param tables? string[]
function nitr.test.db.truncate(tables) end

---Seeds the database in one transaction.
---@param spec string|table A SQL file under `[testing] dir` (a regular file, no `..`), or `{ table = { { column = value }, ... } }` inserted with bound parameters.
function nitr.test.db.seed(spec) end

---Restores the snapshot after every test of this file.
function nitr.test.db.isolate() end

---The configuration snapshot returned by `config.lua` (nil without one). (set when a `config_script` is configured)
nitr.cfg = {}

---User-defined Rust extension modules (`ServerBuilder::module`), one level below the standard library so no future builtin can collide with them. Each module is a table: `nitr.ext.<name>`. Absent until a module is registered.
nitr.ext = {}

